### ISSUE TITLE
Update Contributing.md

### ISSUE THREAD

**Issue by unrealapex** [unrealapex/yt-player#56]
Update Contributing.md to incorporate some of the latest changes from code refactorings.

**Comment by iadnanmalik** [comment]
Hey, I want to contribute. It'll be first open source commit.

**Comment by UnrealApex** [comment]
Sure, shoot a PR and I will review it.

**Comment by iadnanmalik** [comment]
Just looked into it, can you tell which specific change you need to be incorporated in the file, because it seems to be updated.

**Comment by UnrealApex** [comment]
Some of the things that I need in the file are a breakdown of all the project's functions(what they do and how they are related to the functions that call them) and some of the coding conventions that are used in the project like
- using [Prettier](https://prettier.io/) to format code
- preferring double quotes over single quotes
- spaces instead of indents
- 2 space indents
One big thing would be explaining the regex pattern used to manipulate strings and extract values that the player uses to play videos and provide other functionality.

**Comment by UnrealApex** [comment]
@iadnanmalik any update on this?

**Comment by iadnanmalik** [comment]
Sorry, got super busy!!!

**Comment by UnrealApex** [comment]
@iadnanmalik if you are unable to work on this shall I unassign you and work on it myself?
